/**
***************************************************************************
* @file brick/computerVision/calibrationTools.hh
*
* Header file declaring utility routines for use in calibrating sensors.
*
* Copyright (C) 2009-2012 David LaRose, dlr@cs.cmu.edu
* See accompanying file, LICENSE.TXT, for details.
*
***************************************************************************
*/

#ifndef BRICK_COMPUTERVISION_CALIBRATIONTOOLS_HH
#define BRICK_COMPUTERVISION_CALIBRATIONTOOLS_HH

#include <brick/computerVision/cameraIntrinsicsPinhole.hh>
#include <brick/numeric/transform3D.hh>

namespace brick {

  namespace computerVision {
    
    /** 
     * This function estimates camera intrinsic parameters for
     * "complicated" types of camera intrinsics that require nonlinear
     * optimization.  It differs from the function
     * estimateCameraParameters() in that the 3D points must be
     * expressed in camera coordinates (i.e., the camera extrinsics
     * must already be known).  It differs from the function
     * estimateCameraIntrinsicsPinhole() in that it tries to recover
     * lens distortion parameters.  The estimation is based on
     * corresponding points in 2D image coordinates and 3D camera
     * coordinates.  If this function fails to estimate the intrinsics
     * based on the input points, it will throw ValueException.
     *
     * @param numPixelsX This argument specifies the number of columns
     * in images generated by the camera for which intrinsics are
     * being estimated.
     * 
     * @param numPixelsY This argument specifies the number of columns
     * in images generated by the camera for which intrinsics are
     * being estimated.
     * 
     * @param points3DBegin This argument is an iterator pointing to
     * the beginning of a sequence of 3D points (expressed as
     * brick::numeric::Vector3D<Intrinsics::FloatType> instances) in
     * camera coordinates.  The minimum length of this sequence
     * depends on the type of camera intrinsics being estimated.
     * 
     * @param points3DEnd This argument is an iterator pointing one
     * element past the end of the sequence of 3D points in camera
     * coordinates (following the standard library iterator
     * convention).
     * 
     * @param points2DBegin This argument is an iterator pointing to
     * the beginning of a sequence of 2D points (expressed as
     * brick::numeric::Vector2D<Intrinsics::FloatType> instances) in
     * pixel coordinates, corresponding to the the sequence defined by
     * points3DBegin and points3DEnd.  Each element of this sequence
     * must be the projection of the corresponding element of the
     * sequence of 3D points.
     * 
     * @param verbosity This argument sets the level of standard
     * output generated by the function call (0 means none).
     *
     * @return The return value is an estimated camera intrinsics
     * instance that optimally (or as close as possible to optimally,
     * depending on implementation) projects the 3D points to to the
     * corresponding 2D points.
     */
    template <class Intrinsics, class Iter3D, class Iter2D>
    Intrinsics
    estimateCameraIntrinsics(unsigned int numPixelsX,
                             unsigned int numPixelsY,
                             Iter3D points3DBegin,
                             Iter3D points3DEnd,
                             Iter2D points2DBegin,
                             int verbosity = 0);

    
    /** 
     * This function estimates pinhole camera intrinsic parameters
     * based on corresponding points in 2D image coordinates and 3D
     * camera coordinates.  It differs from the function
     * estimateCameraParametersPinhole() in that the 3D points must be
     * expressed in camera coordinates (i.e., the camera extrinsics
     * must already be known).  It differs from the function
     * estimateCameraIntrinsics() in that it does not try to recover
     * lens distortion parameters.  If it is not possible to compute a
     * valid CameraIntrinsicsPinhole instance from the input points,
     * this function will throw ValueException.
     *
     * @param numPixelsX This argument specifies the number of columns
     * in images corresponding to this pinhole camera.  It is copied
     * directly in to the return value, and does not otherwise affect
     * the operation of this function.
     * 
     * @param numPixelsY This argument specifies the number of columns
     * in images corresponding to this pinhole camera.  It is copied
     * directly in to the return value, and does not otherwise affect
     * the operation of this function.
     * 
     * @param points3DBegin This argument is an iterator pointing to
     * the beginning of a sequence of 3D points (expressed as
     * brick::numeric::Vector3D<Intrinsics::FloatType> instances) in
     * camera coordinates.  The sequence must contain at least 3
     * elements.
     * 
     * @param points3DEnd This argument is an iterator pointing one
     * element past the end of the sequence of 3D points in camera
     * coordinates (following the standard library iterator
     * convention).
     * 
     * @param points2DBegin This argument is an iterator pointing to
     * the beginning of a sequence of 2D points (expressed as
     * brick::numeric::Vector2D<Intrinsics::FloatType> instances) in
     * pixel coordinates, corresponding to the the sequence defined by
     * points3DBegin and points3DEnd.  Each element of this sequence
     * must be the projection of the corresponding element of the
     * sequence of 3D points.
     * 
     * @return The return value is a CameraIntrinsicsPinhole instance
     * that optimally (in the least squares sense) projects the 3D
     * points to to the corresponding 2D points.
     */
    template <class FloatType, class Iter3D, class Iter2D>
    CameraIntrinsicsPinhole<FloatType>
    estimateCameraIntrinsicsPinhole(unsigned int numPixelsX,
                                    unsigned int numPixelsY,
                                    Iter3D points3DBegin,
                                    Iter3D points3DEnd,
                                    Iter2D points2DBegin);


    
    /** 
     * This function estimates camera intrinsic and extrinsic
     * parameters for "complicated" types of camera intrinsics that
     * require nonlinear optimization.  It differs from the function
     * estimateCameraIntrinsics() in that the 3D points are expressed
     * in world coordinates, and the camera extrinsics (the position
     * of the camera with respect to the world) are estimated.  It
     * differs from the function estimateCameraParametersPinhole() in
     * that it tries to recover lens distortion parameters.  The
     * estimation is based on corresponding points in 2D image
     * coordinates and 3D world coordinates.  If this function fails
     * to estimate the intrinsics based on the input points, it will
     * throw ValueException.
     *
     * @param intrinsics This reference argument is used to return the
     * estimated camera intrinsics.
     *
     * @param cameraTworld This reference argument is used to return
     * the estimated coordinate transformation that takes world
     * coordinates and returns the corresponding camera coordinates.
     * 
     * @param numPixelsX This argument specifies the number of columns
     * in images generated by the camera for which intrinsics are
     * being estimated.
     * 
     * @param numPixelsY This argument specifies the number of columns
     * in images generated by the camera for which intrinsics are
     * being estimated.
     * 
     * @param points3DBegin This argument is an iterator pointing to
     * the beginning of a sequence of 3D points (expressed as
     * brick::numeric::Vector3D<Intrinsics::FloatType> instances) in
     * world coordinates.  The minimum length of this sequence depends
     * on the type of camera intrinsics being estimated.
     * 
     * @param points3DEnd This argument is an iterator pointing one
     * element past the end of the sequence of 3D points in camera
     * coordinates (following the standard library iterator
     * convention).
     * 
     * @param points2DBegin This argument is an iterator pointing to
     * the beginning of a sequence of 2D points (expressed as
     * brick::numeric::Vector3D<Intrinsics::FloatType> instances) in
     * pixel coordinates, corresponding to the the sequence defined by
     * points3DBegin and points3DEnd.  Each element of this sequence
     * must be the projection of the corresponding element of the
     * sequence of 3D points.
     * 
     * @param verbosity This argument sets the level of standard
     * output generated by the function call (0 means none).
     */
    template <class Intrinsics, class Iter3D, class Iter2D>
    void
    estimateCameraParameters(
      Intrinsics& intrinsics,
      numeric::Transform3D<typename Intrinsics::FloatType>& cameraTworld,
      unsigned int numPixelsX, unsigned int numPixelsY,
      Iter3D points3DBegin, Iter3D points3DEnd,
      Iter2D points2DBegin,
      int verbosity = 0);
    
    
    /** 
     * This function estimates pinhole camera intrinsic and extrinsic
     * parameters based on corresponding points in 2D image
     * coordinates and 3D world coordinates.  It differs from the
     * function estimateCameraIntrinsicsPinhole() in that the 3D
     * points are expressed in world coordinates, and the camera
     * extrinsics (the position of the camera with respect to the
     * world) are estimated.  It is also less accurate.  It differs
     * from the function estimateCameraParameters() in that it does
     * not try to recover lens distortion parameters.
     *
     * The transformation between world coordinates
     * and camera coordinates will be estimated and returned via
     * reference argument cameraTworld.  If it is not possible to
     * compute a valid CameraIntrinsicsPinhole instance from the input
     * points, this function will throw ValueException.
     *
     * @param intrinsics This reference argument is used to return the
     * estimated camera intrinsics.
     *
     * @param cameraTworld This reference argument is used to return
     * the estimated coordinate transformation that takes world
     * coordinates and returns the corresponding camera coordinates.
     * 
     * @param numPixelsX This argument specifies the number of columns
     * in images corresponding to this pinhole camera.  It is copied
     * directly in to the return value, and does not otherwise affect
     * the operation of this function.
     * 
     * @param numPixelsY This argument specifies the number of columns
     * in images corresponding to this pinhole camera.  It is copied
     * directly in to the return value, and does not otherwise affect
     * the operation of this function.
     * 
     * @param points3DBegin This argument is an iterator pointing to
     * the beginning of a sequence of 3D points (expressed as
     * brick::numeric::Vector3D<Intrinsics::FloatType> instances) in
     * world coordinates.  The sequence must contain at least 3
     * elements.
     * 
     * @param points3DEnd This argument is an iterator pointing one
     * element past the end of the sequence of 3D points in world
     * coordinates (following the standard library iterator
     * convention).
     * 
     * @param points2DBegin This argument is an iterator pointing to
     * the beginning of a sequence of 2D points (expressed as
     * brick::numeric::Vector2D<Intrinsics::FloatType> instances) in
     * pixel coordinates, corresponding to the the sequence defined by
     * points3DBegin and points3DEnd.  Each element of this sequence
     * must be the projection of the corresponding element of the
     * sequence of 3D points in world coordinates.
     */
    template <class FloatType, class Iter3D, class Iter2D>
    void
    estimateCameraParametersPinhole(
      CameraIntrinsicsPinhole<FloatType>& intrinsics,
      numeric::Transform3D<FloatType>& cameraTworld,
      unsigned int numPixelsX,
      unsigned int numPixelsY,
      Iter3D points3DBegin,
      Iter3D points3DEnd,
      Iter2D points2DBegin);


  } // namespace computerVision
  
} // namespace brick


// Include file containing definitions of inline and template
// functions.
#include <brick/computerVision/calibrationTools_impl.hh>

#endif /* #ifndef BRICK_COMPUTERVISION_CALIBRATIONTOOLS_HH */
